### PR TITLE
Fix #171 (History corruption on close)

### LINKED ISSUE #171: Bug: Current tab history is corrupted when switcher closes
Steps to reproduce (on Obsidian 1.2.8):

1. Open a series of documents in a tab by navigating links (either between notes or using folder pane, bookmarks, etc.)
2. Drop down the back history list to see how many items there are and in what order
3. Open a switcher
4. Close it
5. Drop down the back history list again -- items are missing from the list that was seen in step 2

If you actually open a file, it does the same thing - the item before the note open in step 1 is removed from the tab's history.

### PR DESCRIPTION
**Pull request by pjeby**
This PR drops all the history manipulation code and instead does previews in-place in history (so the history of the current tab never changes).  Basically, instead of relying on the undocumented internals of Obsidian history, this new version relies on the undocumented `popstate` field in ViewState (that updates the current state without affecting history).

### CODE REVIEW

File: src/app-helper.ts [hunk 1]
```diff
@@ -341,71 +324,81 @@ export class AppHelper {
     return abstractFile as TFile;
   }
 
-  openFile(file: TFile, option: Partial<OpenFileOption> = {}) {
+  captureState(): CaptureState {
+    const leaf = app.workspace.getLeaf();
```
Comment (kometenstaub) [inline src/app-helper.ts:328]: This may need to be changed.

**Comment by pjeby** [comment]
This is now updated to address #157 as well, in that its behavior will fully match that of the standard Obsidian quick switcher with regard to creating tabs, even if you use the preview function, have no unpinned/navigable tabs, and cancel instead of opening files.

**Comment by tadashi-aikawa** [comment]
@pjeby 
I've tested it thoroughly, and it worked perfectly. The code is now cleaner, and I am very grateful. Thank you for your great work!
